export enum KnockoutStageGame {
    ROUND_16_GAME1 = 'ROUND_16_GAME1',
    ROUND_16_GAME2 = 'ROUND_16_GAME2',
    ROUND_16_GAME3 = 'ROUND_16_GAME3',
    ROUND_16_GAME4 = 'ROUND_16_GAME4',
    ROUND_16_GAME5 = 'ROUND_16_GAME5',
    ROUND_16_GAME6 = 'ROUND_16_GAME6',
    ROUND_16_GAME7 = 'ROUND_16_GAME7',
    ROUND_16_GAME8 = 'ROUND_16_GAME8',
    QUARTERFINAL_GAME1 = 'QUARTERFINAL_GAME1',
    QUARTERFINAL_GAME2 = 'QUARTERFINAL_GAME2',
    QUARTERFINAL_GAME3 = 'QUARTERFINAL_GAME3',
    QUARTERFINAL_GAME4 = 'QUARTERFINAL_GAME4',
    SEMIFINAL_GAME1 = 'SEMIFINAL_GAME1',
    SEMIFINAL_GAME2 = 'SEMIFINAL_GAME2',
    FINAL = 'FINAL'
}
